<?php
/**
 * EmailingOptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmailingOptionTest Class Doc Comment
 *
 * @category    Class
 * @description Structure describing an email
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailingOptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmailingOption"
     */
    public function testEmailingOption()
    {
    }

    /**
     * Test attribute "mirror"
     */
    public function testPropertyMirror()
    {
    }

    /**
     * Test attribute "mirror_paragraph"
     */
    public function testPropertyMirrorParagraph()
    {
    }

    /**
     * Test attribute "encoding"
     */
    public function testPropertyEncoding()
    {
    }

    /**
     * Test attribute "importance"
     */
    public function testPropertyImportance()
    {
    }

    /**
     * Test attribute "content_format"
     */
    public function testPropertyContentFormat()
    {
    }

    /**
     * Test attribute "recipient_display"
     */
    public function testPropertyRecipientDisplay()
    {
    }

    /**
     * Test attribute "redirect_bounce"
     */
    public function testPropertyRedirectBounce()
    {
    }

    /**
     * Test attribute "redirect_validation"
     */
    public function testPropertyRedirectValidation()
    {
    }

    /**
     * Test attribute "routing_option"
     */
    public function testPropertyRoutingOption()
    {
    }

    /**
     * Test attribute "analytics_option"
     */
    public function testPropertyAnalyticsOption()
    {
    }

    /**
     * Test attribute "xiti_prefix"
     */
    public function testPropertyXitiPrefix()
    {
    }

    /**
     * Test attribute "xiti_tag"
     */
    public function testPropertyXitiTag()
    {
    }

    /**
     * Test attribute "ga_source"
     */
    public function testPropertyGaSource()
    {
    }

    /**
     * Test attribute "ga_medium"
     */
    public function testPropertyGaMedium()
    {
    }

    /**
     * Test attribute "ga_campaign"
     */
    public function testPropertyGaCampaign()
    {
    }

    /**
     * Test attribute "ga_content"
     */
    public function testPropertyGaContent()
    {
    }

    /**
     * Test attribute "ga_term"
     */
    public function testPropertyGaTerm()
    {
    }

    /**
     * Test attribute "ga_prefix"
     */
    public function testPropertyGaPrefix()
    {
    }
}
