<?php
/**
 * PartnerSignUpTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PartnerSignUpTest Class Doc Comment
 *
 * @category    Class
 * @description Class holding data related to adding an account
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PartnerSignUpTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PartnerSignUp"
     */
    public function testPartnerSignUp()
    {
    }

    /**
     * Test attribute "mbcode"
     */
    public function testPropertyMbcode()
    {
    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "jobtitle"
     */
    public function testPropertyJobtitle()
    {
    }

    /**
     * Test attribute "phonenumber"
     */
    public function testPropertyPhonenumber()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "zipcode"
     */
    public function testPropertyZipcode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "culture"
     */
    public function testPropertyCulture()
    {
    }

    /**
     * Test attribute "sending_emails"
     */
    public function testPropertySendingEmails()
    {
    }

    /**
     * Test attribute "reseller_nfo"
     */
    public function testPropertyResellerNfo()
    {
    }

    /**
     * Test attribute "website"
     */
    public function testPropertyWebsite()
    {
    }
}
