<?php
/**
 * ReceiversOperationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ReceiversOperationTest Class Doc Comment
 *
 * @category    Class
 * @description This contain the different possible selection of contacts for an operation.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReceiversOperationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ReceiversOperation"
     */
    public function testReceiversOperation()
    {
    }

    /**
     * Test attribute "segment_ids"
     */
    public function testPropertySegmentIds()
    {
    }

    /**
     * Test attribute "import_ids"
     */
    public function testPropertyImportIds()
    {
    }

    /**
     * Test attribute "contact_ids"
     */
    public function testPropertyContactIds()
    {
    }

    /**
     * Test attribute "conditions_xml"
     */
    public function testPropertyConditionsXml()
    {
    }

    /**
     * Test attribute "conditions_mode"
     */
    public function testPropertyConditionsMode()
    {
    }
}
