<?php
/**
 * AccountApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AccountApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccountApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountDeleteContactAttribute
     *
     * Supprimer définitivement un champ.
     *
     */
    public function testAccountDeleteContactAttribute()
    {
    }

    /**
     * Test case for accountDeleteContactAttributeValue
     *
     * Supprimer définitivement une valeur d'un champ.
     *
     */
    public function testAccountDeleteContactAttributeValue()
    {
    }

    /**
     * Test case for accountGetAccountCredits
     *
     * Obtenir les credits restant   Vous pouvez choisir entre transactional, sms ou marketing.
     *
     */
    public function testAccountGetAccountCredits()
    {
    }

    /**
     * Test case for accountGetAccountSettings
     *
     * Get an account attribute field.
     *
     */
    public function testAccountGetAccountSettings()
    {
    }

    /**
     * Test case for accountGetAllContactAttribute
     *
     * Obtenir la liste des champs de la base de contact.
     *
     */
    public function testAccountGetAllContactAttribute()
    {
    }

    /**
     * Test case for accountGetAllContactAttributeValues
     *
     * Obtenir la valeur d'un champ spécifique.
     *
     */
    public function testAccountGetAllContactAttributeValues()
    {
    }

    /**
     * Test case for accountGetContactAttribute
     *
     * Obtenir les informations d'un champ.
     *
     */
    public function testAccountGetContactAttribute()
    {
    }

    /**
     * Test case for accountPostAccountSettings
     *
     * Update an account attributes fields.
     *
     */
    public function testAccountPostAccountSettings()
    {
    }

    /**
     * Test case for accountPostContactAttribute
     *
     * Ajouter un nouveau champ dans la base contact.
     *
     */
    public function testAccountPostContactAttribute()
    {
    }

    /**
     * Test case for accountPostContactAttributeValue
     *
     * Ajouter une nouvelle valeur pour le champ spécifié (sélection unique ou multiple seulement).
     *
     */
    public function testAccountPostContactAttributeValue()
    {
    }

    /**
     * Test case for accountPutContactAttribute
     *
     * Mettre à jour le nom d'un champ.
     *
     */
    public function testAccountPutContactAttribute()
    {
    }

    /**
     * Test case for accountPutContactAttributeValue
     *
     * Mettre à jour de la valeur du champ en changeant le nom et/ou l'index.
     *
     */
    public function testAccountPutContactAttributeValue()
    {
    }
}
