<?php
/**
 * ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for contactDeleteContactById
     *
     * Supprimer définitivement un contact.
     *
     */
    public function testContactDeleteContactById()
    {
    }

    /**
     * Test case for contactDeleteContactByKey
     *
     * Supprimer définitivement un contact.
     *
     */
    public function testContactDeleteContactByKey()
    {
    }

    /**
     * Test case for contactGetContacHistory
     *
     * Obtenir la liste des activités d'un contact.
     *
     */
    public function testContactGetContacHistory()
    {
    }

    /**
     * Test case for contactGetContactAttributeId
     *
     * Obtenir la liste des champs et leur valeur.
     *
     */
    public function testContactGetContactAttributeId()
    {
    }

    /**
     * Test case for contactGetContactAttributeIdKey
     *
     * Obtenir une valeur spécifique avec la clé d'unicité.
     *
     */
    public function testContactGetContactAttributeIdKey()
    {
    }

    /**
     * Test case for contactGetContactAttributeIdbyId
     *
     * Obtenir un champ et sa valeur.
     *
     */
    public function testContactGetContactAttributeIdbyId()
    {
    }

    /**
     * Test case for contactGetContactAttributeKey
     *
     * Obtenir la liste des informations d'un contact.
     *
     */
    public function testContactGetContactAttributeKey()
    {
    }

    /**
     * Test case for contactPostContacHistory
     *
     * Ajouter une activité à un contact suite à une opération.
     *
     */
    public function testContactPostContacHistory()
    {
    }

    /**
     * Test case for contactPostContactAttributeKey
     *
     * Créer ou mettre à jour les informations d'un contact.
     *
     */
    public function testContactPostContactAttributeKey()
    {
    }

    /**
     * Test case for contactPutContactAttributeKey
     *
     * Mettre à jour des informations du contact.
     *
     */
    public function testContactPutContactAttributeKey()
    {
    }
}
