<?php
/**
 * ContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for contactsDeleteDelete
     *
     * Supprimer définitivement une précédente purge.
     *
     */
    public function testContactsDeleteDelete()
    {
    }

    /**
     * Test case for contactsDeleteExport
     *
     * Supprimer définitivement un export.
     *
     */
    public function testContactsDeleteExport()
    {
    }

    /**
     * Test case for contactsDeleteImport
     *
     * Supprimer définitivement les information d'un précedent import.
     *
     */
    public function testContactsDeleteImport()
    {
    }

    /**
     * Test case for contactsGetDelete
     *
     * Obtenir les informations d'une précédente purge.
     *
     */
    public function testContactsGetDelete()
    {
    }

    /**
     * Test case for contactsGetDeleteList
     *
     * Obtenir la liste des précédentes purges.
     *
     */
    public function testContactsGetDeleteList()
    {
    }

    /**
     * Test case for contactsGetExport
     *
     * Obtenir les informations d'un précédent export.
     *
     */
    public function testContactsGetExport()
    {
    }

    /**
     * Test case for contactsGetExportList
     *
     * Obtenir la liste des précédents exports.
     *
     */
    public function testContactsGetExportList()
    {
    }

    /**
     * Test case for contactsGetFileDelete
     *
     * Télécharger le fichier d'archive de la purge.
     *
     */
    public function testContactsGetFileDelete()
    {
    }

    /**
     * Test case for contactsGetFileExport
     *
     * Télécharger le fichier d'archive de l'export.
     *
     */
    public function testContactsGetFileExport()
    {
    }

    /**
     * Test case for contactsGetFileImport
     *
     * Télécharger le fichier d'archive d'un import.
     *
     */
    public function testContactsGetFileImport()
    {
    }

    /**
     * Test case for contactsGetImport
     *
     * Obtenir les informations d'un précédent import.
     *
     */
    public function testContactsGetImport()
    {
    }

    /**
     * Test case for contactsGetImportList
     *
     * Obtenir la liste des précédents imports.
     *
     */
    public function testContactsGetImportList()
    {
    }

    /**
     * Test case for contactsPostContactsAttributeKey
     *
     * Créer ou mettre à jour des informations de contacts (jusqu'à 500).
     *
     */
    public function testContactsPostContactsAttributeKey()
    {
    }

    /**
     * Test case for contactsPostDeleteOperation
     *
     * Effectuer une purge à partir d'un fichier.
     *
     */
    public function testContactsPostDeleteOperation()
    {
    }

    /**
     * Test case for contactsPostExportOperation
     *
     * Lancer un nouvel export de la base de contact.
     *
     */
    public function testContactsPostExportOperation()
    {
    }

    /**
     * Test case for contactsPostImportOperation
     *
     * Effectuer un nouvel import dans la base de contacts.
     *
     */
    public function testContactsPostImportOperation()
    {
    }

    /**
     * Test case for contactsPutContactAttributeKey
     *
     * Mettre à jour des informations de contacts (jusqu'à 500).
     *
     */
    public function testContactsPutContactAttributeKey()
    {
    }
}
