<?php
/**
 * EmailingApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EmailingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmailingApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for emailingApproveEmailingOperation
     *
     * Valider l'envoi d'une opération.
     *
     */
    public function testEmailingApproveEmailingOperation()
    {
    }

    /**
     * Test case for emailingDeleteSingleEmailingOperation
     *
     * Supprimer définitivement une opération.
     *
     */
    public function testEmailingDeleteSingleEmailingOperation()
    {
    }

    /**
     * Test case for emailingGetAllEmailingOperation
     *
     * Obtenir la liste des opérations.
     *
     */
    public function testEmailingGetAllEmailingOperation()
    {
    }

    /**
     * Test case for emailingGetAllExportEmailingOperation
     *
     * Obtenir la liste de tous les exports d'activités sur les destinataires d'opérations.
     *
     */
    public function testEmailingGetAllExportEmailingOperation()
    {
    }

    /**
     * Test case for emailingGetExportEmailingOperation
     *
     * Obtenir les informations d'un export d'activités sur les destinataires d'une opération.
     *
     */
    public function testEmailingGetExportEmailingOperation()
    {
    }

    /**
     * Test case for emailingGetFileExport
     *
     * Télécharger le fichier d'archive de l'export.
     *
     */
    public function testEmailingGetFileExport()
    {
    }

    /**
     * Test case for emailingGetSingleEmailingOperation
     *
     * Obtenir les informations d'une opération.
     *
     */
    public function testEmailingGetSingleEmailingOperation()
    {
    }

    /**
     * Test case for emailingGetStatusEmailingOperation
     *
     * Obtenir les opérations par status.
     *
     */
    public function testEmailingGetStatusEmailingOperation()
    {
    }

    /**
     * Test case for emailingPostEmailingOperation
     *
     * Créer une opération.
     *
     */
    public function testEmailingPostEmailingOperation()
    {
    }

    /**
     * Test case for emailingPostExportEmailingOperation
     *
     * Ajouter un export d'activités sur les destinataires d'une opération spécifique.
     *
     */
    public function testEmailingPostExportEmailingOperation()
    {
    }

    /**
     * Test case for emailingPostSendSmtp
     *
     * Faire un envoi SMTP Transactionnel en reprenant le contenu HTML et TEXT d'une opération spécifique.
     *
     */
    public function testEmailingPostSendSmtp()
    {
    }

    /**
     * Test case for emailingPostTestOperation
     *
     * Envoyer un email de test.
     *
     */
    public function testEmailingPostTestOperation()
    {
    }

    /**
     * Test case for emailingPutEmailingOperation
     *
     * Mettre à jour une opération.
     *
     */
    public function testEmailingPutEmailingOperation()
    {
    }

    /**
     * Test case for emailingResumeEmailingOperation
     *
     * Reprendre une opération.
     *
     */
    public function testEmailingResumeEmailingOperation()
    {
    }

    /**
     * Test case for emailingSearchEmailingOperation
     *
     * Recherche d'une opération en fonction des paramètres.
     *
     */
    public function testEmailingSearchEmailingOperation()
    {
    }

    /**
     * Test case for emailingSuspendEmailingOperation
     *
     * Suspendre une opération.
     *
     */
    public function testEmailingSuspendEmailingOperation()
    {
    }
}
