<?php
/**
 * SegmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SegmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SegmentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for segmentDeleteSegment
     *
     * Supprimer définitivement un segment.
     *
     */
    public function testSegmentDeleteSegment()
    {
    }

    /**
     * Test case for segmentGetAllSegments
     *
     * Obtenir la liste de segments.
     *
     */
    public function testSegmentGetAllSegments()
    {
    }

    /**
     * Test case for segmentGetSegment
     *
     * Obtenir un segment.
     *
     */
    public function testSegmentGetSegment()
    {
    }

    /**
     * Test case for segmentPostSegment
     *
     * Ajouter un nouveau segment.
     *
     */
    public function testSegmentPostSegment()
    {
    }

    /**
     * Test case for segmentPutSegment
     *
     * Mettre à jour d'un segment.
     *
     */
    public function testSegmentPutSegment()
    {
    }

    /**
     * Test case for segmentUpdateSegmentCache
     *
     * Mettre à jour le comptage du segment.
     *
     */
    public function testSegmentUpdateSegmentCache()
    {
    }
}
