<?php
/**
 * SmsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Sendethic API
 *
 * REST API allowing you to interact with your Sendethic account.
 *
 * OpenAPI spec version: v4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.39
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SmsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SmsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for smsApproveSmsOperation
     *
     * Valider l'envoi d'une opération.
     *
     */
    public function testSmsApproveSmsOperation()
    {
    }

    /**
     * Test case for smsDeleteSingleSmsOperation
     *
     * Supprimer définitivement une opération.
     *
     */
    public function testSmsDeleteSingleSmsOperation()
    {
    }

    /**
     * Test case for smsGetAllSmsOperation
     *
     * Obtenir la liste des opérations.
     *
     */
    public function testSmsGetAllSmsOperation()
    {
    }

    /**
     * Test case for smsGetSingleSmsOperation
     *
     * Obtenir les informations d'une opération.
     *
     */
    public function testSmsGetSingleSmsOperation()
    {
    }

    /**
     * Test case for smsGetStatusSmsOperation
     *
     * Obtenir les opérations par status.
     *
     */
    public function testSmsGetStatusSmsOperation()
    {
    }

    /**
     * Test case for smsPostSmsOperation
     *
     * Créer une opération.
     *
     */
    public function testSmsPostSmsOperation()
    {
    }

    /**
     * Test case for smsPutSmsOperation
     *
     * Mettre à jour une opération.
     *
     */
    public function testSmsPutSmsOperation()
    {
    }

    /**
     * Test case for smsResumeSmsOperation
     *
     * Reprendre une opération.
     *
     */
    public function testSmsResumeSmsOperation()
    {
    }

    /**
     * Test case for smsSearchEmailingOperation
     *
     * Recherche d'une opération en fonction des paramètres.
     *
     */
    public function testSmsSearchEmailingOperation()
    {
    }

    /**
     * Test case for smsSendSms
     *
     * Envoyer un sms.
     *
     */
    public function testSmsSendSms()
    {
    }

    /**
     * Test case for smsSuspendSmsOperation
     *
     * Suspendre une opération.
     *
     */
    public function testSmsSuspendSmsOperation()
    {
    }
}
